### PR TITLE
Stop login action execution on serverError.

### PR DESCRIPTION
**Pull request by aars**
Otherwise "headers already sent" error will crash application.

### CODE REVIEW

**Comment by listepo** [comment]
+1

**Comment by wayne-o** [comment]
:+1:

**Comment by Globegitter** [comment]
LGTM.

**Comment by wayne-o** [comment]
:+1:  i have noticed this exception crash my API  - would be good to get this merged in

**Comment by Globegitter** [comment]
Not sure why coverall has issues but it is looking good to me.

**Comment by Globegitter** [comment]
Oh could you please add this change to the `CHANGELOG.md` @aars ?

**Comment by aars** [comment]
I did in a seperate PR here https://github.com/waterlock/waterlock-local-auth/pull/31

Will keep that in mind in the future :+1:

**Pull request merged**
