### PR TITLE
Add bugfix to changelog

### PR DESCRIPTION
**Pull request by aars**
I don't believe I'm able to bump the version, right? So that should probably be done to reflect the changelog :)

### CODE REVIEW

**Comment by Globegitter** [comment]
@aars 0.0.6 isn't actually released yet. So put it there, then I can merge and I will also push a release.

**Comment by aars** [comment]
@Globegitter Oopsie :D Fixed.

**Comment by Globegitter** [comment]
Thank you!

**Comment by Globegitter** [comment]
@aars version is published.

**Pull request merged**
