### PR TITLE
adding /register endpoint to local-auth

### PR DESCRIPTION
**Pull request by wayne-o**
This adds an explicit /register endpoint to waterlock-local-auth

Throws if the email is already registered

### CODE REVIEW

**Comment by wayne-o** [comment]
Depends on https://github.com/waterlock/waterlock/pull/76

**Comment by elennaro** [comment]
Hi, and thanks for a cool library!

When do you plan to implement this?
I'm running into [this issue](https://github.com/waterlock/waterlock/issues/83#issuecomment-97421107) due to lack of register module in this module.

**Comment by wayne-o** [comment]
I think I just need to update the docs on https://github.com/waterlock/waterlock/pull/76 and we can get it all merged in. I've been away from all this for a while so I will refresh my memory and get on it as soon as I can. 

If anyone else has time to update the docs please feel free

**Comment by elennaro** [comment]
Thanks @wayne-o.

**Comment by carlospliego** [comment]
Any update on this issue?

**Comment by wayne-o** [comment]
I've just merged this in

**Pull request closed without merging**
